### ISSUE TITLE
Authorize URL should not be under api.fitbit.com

### ISSUE THREAD

**Issue by ElMassimo** [whazzmaster/fitgem#38] opened 2015-05-19 21:56 UTC
According to the [Fitbit](https://wiki.fitbit.com/display/API/OAuth+1.0a+Authentication#OAuth1.0aAuthentication-TheclientredirectstheusertoFitbitinorderfortheusertoauthorizetheclientapplication.) documentation, in order for the users to authorize the client application, users should be redirected to:
__https://www.fitbit.com/oauth/authorize?oauth_token=<temporary-token>[&locale=<locale>][&display=touch][&requestCredentials=true]__

With the current configuration, it seems like users are being redirected to https://api.fitbit.com/oauth/authorize.

According to fitbit support, there are __two reasons__ to use the non-api URL:

1. When you send people to api.fitbit.com, they are always required to sign in to authorize your app. When your app uses the correct URL, people do not have to sign in if they are already signed in on the device.
2. While Fitbit has supported authorization on api.fitbit.com, soon it will begin redirecting these requests to www.fitbit.com, which will increase the page load time for your users.

**Comment by jeremiahlee** [comment] 2015-05-19 22:38
Hello, I'm the API lead at Fitbit. I can confirm that the OAuth 1.0a authorization URL should use www.fitbit.com. I know many developers have used Fitgem and this change would be valuable to them for the reasons above.

**Comment by whazzmaster** [comment] 2015-05-26 23:43
Apologies- work has been hectic lately. I'll get PR #39 merged and see if I can cut a new gem version tonight.

**Comment by whazzmaster** [comment] 2015-05-26 23:57
One question @jeremiahlee; so all API requests continue to hit api.fitbit.com and it's just the OAuth authorize call that needs to go to www.fitbit.com?

**Comment by whazzmaster** [comment] 2015-05-27 00:59
Closed by #39

**Closed by whazzmaster** 2015-05-27 00:59 UTC
